export const UPDATE_PAGE ='UPDATE_PAGE';
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';
export const UPDATE_YEAR = 'UPDATE_YEAR';
export const UPDATE_NATION = 'UPDATE_NATION';
export const CHANGE_DATA_FETCHING = 'CHANGE_DATA_FETCHING';
