export const consolidatedStructure = {
    "conBudgetListEntity": [
      {
        "id": 1,
        "type": "Revenue",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Black",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": null,
        "cyPercentGrowth": null
      },
      {
        "id": 2,
        "type": "Special Event Revenue",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 199000,
        "pyytdActual": 104992,
        "pyttdVariance": -94008,
        "pyttdPercentVariance": -47.24020100503,
        "pyBudget": 199000,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 3,
        "type": "Direct Response",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 4,
        "type": "Less: Direct Special Event Expenses",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": -42250,
        "pyytdActual": -16583,
        "pyttdVariance": 25667,
        "pyttdPercentVariance": 60.75029585799,
        "pyBudget": -42250,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 5,
        "type": "Net Revenue from Special Events",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 156750,
        "pyytdActual": 88409,
        "pyttdVariance": -68341,
        "pyttdPercentVariance": -43.598724082930005,
        "pyBudget": 156750,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 6,
        "type": "Team Challenge",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 7,
        "type": "Less: Direct Team Challenge Expenses",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 8,
        "type": "Net Revenue from Team Challenge",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 9,
        "type": "spin4",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 30000,
        "pyytdActual": 19707,
        "pyttdVariance": -10293,
        "pyttdPercentVariance": -34.31,
        "pyBudget": 30000,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 10,
        "type": "Less: Direct spin4 Expenses",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": -2422,
        "pyytdActual": -324,
        "pyttdVariance": 2098,
        "pyttdPercentVariance": 86.62262592898,
        "pyBudget": -2422,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 11,
        "type": "Net Revenue from spin4",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 27578,
        "pyytdActual": 19383,
        "pyttdVariance": -8195,
        "pyttdPercentVariance": -29.71571542534,
        "pyBudget": 27578,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 12,
        "type": "Take Steps",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 143500,
        "pyytdActual": 160416,
        "pyttdVariance": 16916,
        "pyttdPercentVariance": 11.7881533101,
        "pyBudget": 143500,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 13,
        "type": "Less: Direct Take Steps Expenses",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": -12250,
        "pyytdActual": -9138,
        "pyttdVariance": 3112,
        "pyttdPercentVariance": 25.404081632649998,
        "pyBudget": -12250,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 14,
        "type": "Net Revenue from Take Steps",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 131250,
        "pyytdActual": 151278,
        "pyttdVariance": 20028,
        "pyttdPercentVariance": 15.25942857143,
        "pyBudget": 131250,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 15,
        "type": "Total Gross Event Revenue",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 372500,
        "pyytdActual": 285115,
        "pyttdVariance": -87385,
        "pyttdPercentVariance": -23.45906040268,
        "pyBudget": 372500,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 16,
        "type": "Less: Total Direct Donor Benefit (DDB) Event Expense",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": -56922,
        "pyytdActual": -26045,
        "pyttdVariance": 30877,
        "pyttdPercentVariance": 54.244404623870004,
        "pyBudget": -56922,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 17,
        "type": "Total Net Event Revenue",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Green",
        "pyytdBudget": 315578,
        "pyytdActual": 259070,
        "pyttdVariance": -56508,
        "pyttdPercentVariance": -17.90619117936,
        "pyBudget": 315578,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 18,
        "type": "Individual Major Gifts",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 53000,
        "pyytdActual": 44913,
        "pyttdVariance": -8087,
        "pyttdPercentVariance": -15.25849056604,
        "pyBudget": 53000,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 53000,
        "admin": 0,
        "totalCyBudget": 53000,
        "forecastBudgetVariance": 53000,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 19,
        "type": "Corporate Major Gifts",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 20,
        "type": "Foundation Major Gifts",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 67500,
        "pyytdActual": 65000,
        "pyttdVariance": -2500,
        "pyttdPercentVariance": -3.7037037037,
        "pyBudget": 67500,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 67500,
        "admin": 0,
        "totalCyBudget": 67500,
        "forecastBudgetVariance": 67500,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 21,
        "type": "Corporate Pharma",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 3250,
        "pyttdVariance": 3250,
        "pyttdPercentVariance": 100,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 22,
        "type": "Total Major Gifts",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Green",
        "pyytdBudget": 120500,
        "pyytdActual": 113163,
        "pyttdVariance": -7337,
        "pyttdPercentVariance": -6.0887966805,
        "pyBudget": 120500,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 120500,
        "admin": 0,
        "totalCyBudget": 120500,
        "forecastBudgetVariance": 120500,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 23,
        "type": "Education & Camp Registration ",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 24,
        "type": "Third Party-Events",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 7500,
        "pyytdActual": 1332,
        "pyttdVariance": -6168,
        "pyttdPercentVariance": -82.24000000000001,
        "pyBudget": 7500,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 7500,
        "admin": 0,
        "totalCyBudget": 7500,
        "forecastBudgetVariance": 7500,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 25,
        "type": "Workplace Giving",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 3701,
        "pyytdActual": 6328,
        "pyttdVariance": 2627,
        "pyttdPercentVariance": 70.98081599568,
        "pyBudget": 3701,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 3701,
        "admin": 0,
        "totalCyBudget": 3701,
        "forecastBudgetVariance": 3701,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 26,
        "type": "Royalty ",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 27,
        "type": "Government Grants",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 28,
        "type": "Interest & Dividend Income",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 29,
        "type": "Tributes and Memorials",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 1000,
        "pyytdActual": 2115,
        "pyttdVariance": 1115,
        "pyttdPercentVariance": 111.5,
        "pyBudget": 1000,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 1000,
        "admin": 0,
        "totalCyBudget": 1000,
        "forecastBudgetVariance": 1000,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 30,
        "type": "Clubs & Organizations",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 500,
        "pyytdActual": 0,
        "pyttdVariance": -500,
        "pyttdPercentVariance": -100,
        "pyBudget": 500,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 500,
        "admin": 0,
        "totalCyBudget": 500,
        "forecastBudgetVariance": 500,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 31,
        "type": "Vehicle Organizations",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 32,
        "type": "Investment Portfolio Appropriated for Operations",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 33,
        "type": "Losses and Recoveries",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 34,
        "type": "Miscellaneous Revenue",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 35,
        "type": "Total Other Revenue",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 12701,
        "pyytdActual": 9775,
        "pyttdVariance": -2926,
        "pyttdPercentVariance": -23.03755609795,
        "pyBudget": 12701,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 12701,
        "admin": 0,
        "totalCyBudget": 12701,
        "forecastBudgetVariance": 12701,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 36,
        "type": "Operating Revenue",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 448779,
        "pyytdActual": 382008,
        "pyttdVariance": -66771,
        "pyttdPercentVariance": -14.878369977200002,
        "pyBudget": 448779,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 133201,
        "admin": 0,
        "totalCyBudget": 133201,
        "forecastBudgetVariance": 133201,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 37,
        "type": "Charitable Gift Annuities",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 38,
        "type": "Bequests",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 39,
        "type": "TOTAL GROSS REVENUE",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Green",
        "pyytdBudget": 505701,
        "pyytdActual": 408053,
        "pyttdVariance": -97648,
        "pyttdPercentVariance": -19.30943383541,
        "pyBudget": 505701,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 133201,
        "admin": 0,
        "totalCyBudget": 133201,
        "forecastBudgetVariance": 133201,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 40,
        "type": "TOTAL NET REVENUE",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Green",
        "pyytdBudget": 448779,
        "pyytdActual": 382008,
        "pyttdVariance": -66771,
        "pyttdPercentVariance": -14.878369977200002,
        "pyBudget": 448779,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 133201,
        "admin": 0,
        "totalCyBudget": 133201,
        "forecastBudgetVariance": 133201,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 41,
        "type": "EXPENSES",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Black",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": null,
        "cyPercentGrowth": null
      },
      {
        "id": 42,
        "type": "Research",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 43,
        "type": "Mission - Conference & Symposiums",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 44,
        "type": "Direct Education Programs",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 45,
        "type": "Other Mission Expenditures",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 46,
        "type": "Direct Mission Expenses",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 47,
        "type": "Occupancy",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 2100,
        "pyytdActual": 2539,
        "pyttdVariance": 439,
        "pyttdPercentVariance": 20.90476190476,
        "pyBudget": 2100,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 48,
        "type": "Printing ",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 983,
        "pyytdActual": 966,
        "pyttdVariance": -17,
        "pyttdPercentVariance": -1.72939979654,
        "pyBudget": 983,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 49,
        "type": "Compensation",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 259934,
        "pyytdActual": 171905,
        "pyttdVariance": -88029,
        "pyttdPercentVariance": -33.86590442189,
        "pyBudget": 259934,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 50,
        "type": "Postage & Shipping",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 1756,
        "pyytdActual": 1097,
        "pyttdVariance": -659,
        "pyttdPercentVariance": -37.528473804099995,
        "pyBudget": 1756,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 51,
        "type": "Meetings & Travel",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 5472,
        "pyytdActual": 6390,
        "pyttdVariance": 918,
        "pyttdPercentVariance": 16.77631578947,
        "pyBudget": 5472,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 52,
        "type": "Depreciation",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 302,
        "pyttdVariance": 302,
        "pyttdPercentVariance": 100,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 53,
        "type": "Insurance",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 54,
        "type": "Professional Fees",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 55,
        "type": "List Rental",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 56,
        "type": "Repairs & Maintenance",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 57,
        "type": "Advertising",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 150,
        "pyytdActual": 86,
        "pyttdVariance": -64,
        "pyttdPercentVariance": -42.66666666667,
        "pyBudget": 150,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 58,
        "type": "Bank Charge",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 25,
        "pyytdActual": 96,
        "pyttdVariance": 71,
        "pyttdPercentVariance": 284,
        "pyBudget": 25,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 59,
        "type": "Dues & Subscription",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 450,
        "pyytdActual": 518,
        "pyttdVariance": 68,
        "pyttdPercentVariance": 15.11111111111,
        "pyBudget": 450,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 60,
        "type": "Permit /Licenses/ State Reg.",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 525,
        "pyytdActual": 0,
        "pyttdVariance": -525,
        "pyttdPercentVariance": -100,
        "pyBudget": 525,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 61,
        "type": "Acknowledgement /Recognition",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 450,
        "pyytdActual": 781,
        "pyttdVariance": 331,
        "pyttdPercentVariance": 73.55555555556,
        "pyBudget": 450,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 62,
        "type": "Equipment Rental",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 63,
        "type": "Telecommunications",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 1479,
        "pyytdActual": 1550,
        "pyttdVariance": 71,
        "pyttdPercentVariance": 4.800540906019999,
        "pyBudget": 1479,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 64,
        "type": "Supplies",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 3040,
        "pyytdActual": 2253,
        "pyttdVariance": -787,
        "pyttdPercentVariance": -25.88815789474,
        "pyBudget": 3040,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 65,
        "type": "Contributed Airtime",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 66,
        "type": "Donated Services",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 67,
        "type": "Auction Items",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 68,
        "type": "Provision for Uncollectible Pledges, Discounts, AR",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 0,
        "pyytdActual": 0,
        "pyttdVariance": 0,
        "pyttdPercentVariance": 0,
        "pyBudget": 0,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 69,
        "type": "Miscellaneous",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "No Color",
        "pyytdBudget": 500,
        "pyytdActual": 5000,
        "pyttdVariance": 4500,
        "pyttdPercentVariance": 900,
        "pyBudget": 500,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 70,
        "type": "OPERATING EXPENSES",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Yellow",
        "pyytdBudget": 276864,
        "pyytdActual": 193483,
        "pyttdVariance": -83381,
        "pyttdPercentVariance": -30.116230351360002,
        "pyBudget": 276864,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 71,
        "type": "TOTAL EXPENSES",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Green",
        "pyytdBudget": 276864,
        "pyytdActual": 193483,
        "pyttdVariance": -83381,
        "pyttdPercentVariance": -30.116230351360002,
        "pyBudget": 276864,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      },
      {
        "id": 72,
        "type": "NET SURPLUS (DEFICIT) FROM OPERATIONS",
        "area": "West",
        "chapter": "Central Texas",
        "companyCode": 1515,
        "color": "Green",
        "pyytdBudget": 171915,
        "pyytdActual": 188525,
        "pyttdVariance": 16610,
        "pyttdPercentVariance": 9.66175144694,
        "pyBudget": 171915,
        "pyForecast": 0,
        "specialEvents": 0,
        "spin4": 0,
        "takeSteps": 0,
        "other": 0,
        "admin": 0,
        "totalCyBudget": 0,
        "forecastBudgetVariance": 0,
        "percentVarinace": 0,
        "pyPercentGrowth": 0,
        "cyPercentGrowth": 0
      }
    ]
  }